from typing import Optional
from dataclasses import dataclass, field


@dataclass
class AgentState:
    question: str                        # user's original question
    schema: str = ""                     # DB schema fetched by the schema tool
    sql_query: str = ""                  # SQL generated by the LLM
    sql_result: str = ""                 # raw rows returned from the DB
    answer: str = ""                     # final plain-English answer
    error: str = ""                      # any error message for retry logic
    retry_count: int = 0                 # how many times we have retried
    messages: list = field(default_factory=list)  # full LLM message history
